version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: sante-mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: sante_dossier
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  sonarqube:
    image: sonarqube:community
    container_name: sante-sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sante-dossier-jenkins
    user: root
    ports:
      - "8098:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
      - mysql

volumes:
  jenkins_home: