version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: sante-mysql
    networks:
      - sante-network
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: sante_dossier
    ports:
      - "3311:3306"

  sonarqube:
    image: sonarqube:community
    container_name: sante-sonarqube
    networks:
      - sante-network
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sante-dossier-jenkins
    user: root
    networks:
      - sante-network
    ports:
      - "8098:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
      - mysql

networks:
  sante-network:
    external: false